version: "3"
services:

  client:
    image: pk37/colib-client
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - mern-network
    depends_on:
      - server
    command: npm start
    stdin_open: true
    tty: true
  
  server:
    image: pk37/colib-server
    ports:
      - 5000:5000
    networks:
      - mern-network
    command: npm run server

networks:
  mern-network:
    driver: bridge
