
---
- name: Pull Docker Image
  hosts: all
  tasks:
    - name: docker compose
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: pull images
      command: docker-compose -f ./docker-compose.yml pull
    - name: run the docker images
      command: docker-compose -f ./docker-compose.yml up -d
